apiVersion: v1
kind: ReplicationController
metadata:
 name: xiaomweb
spec:
 replicas: 1
 selector:
   app: xiaomweb
 template:
   metadata:
     labels:
       app: xiaomweb
   spec:
     containers:
     - name: xiaomweb
       image: 39.101.135.227:85/harbor/nginx:latest

---
apiVersion: v1
kind: Service
metadata:
 name: xiaomweb
spec:
 type: NodePort
 ports:
 - port: 9000
   nodePort: 30122 
 selector:
   app: xiaomweb